name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Install Packages Dependencies
        run: yarn bootstrap

      - name: Build packages
        run: yarn build

      - name: Test packages
        run: yarn test

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          version: |
            rm .husky/commit-msg
            git stash
            changeset version
          publish: yarn changeset publish
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}