name: Test packages

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Install Packages Dependencies
        run: yarn bootstrap

      - name: Build packages
        run: yarn build

      - name: Test packages
        run: yarn test
